name: Deploy to cloudtype
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: davidlee1122/springboot-blog-shitahaku-hounensai
          stage: main
          yaml: |
            name: springboot-blog-shitahaku-hounensai
            app: java@17
            options:
              ports: "8000"
              env:
                - name: DB_HOST
                  value: mariadb
                - name: DB_PORT
                  value: "3306"
                - name: DB_NAME
                  value: testdb
                - name: DB_USERNAME
                  value: root
                - name: DB_PASSWORD
                  value: cos1234
              buildenv: []
              includes: src
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot
